version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: classroom_mongodb_noauth
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_noauth:/data/db
    networks:
      - classroom_network

volumes:
  mongodb_data_noauth:

networks:
  classroom_network:
    driver: bridge
